version: '20.10.17'
services:
  app:
    build: 
      context: .
    volumes:
      - .:/hotel-nactar
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start

